### ISSUE TITLE
Challenge and missing levels

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/Challenges#205] opened 2019-12-17 10:31 UTC
Lately every time I restart the server in the console I see messages of this type. Without reason some challenge / levels disappear .. Then reloading them (having a copy) I reload the plugin or restart the server and appear again .. It is not possible however that every time I restart I have to check these things ..

https://imgur.com/rfrPkLH

Version: Challenges-0.8.0-SNAPSHOT-.323

**Comment by BONNe** [comment] 2019-12-17 13:36
Yea... I do not know... probably using development version is not the smartest ways. :)

**Comment by Manu5656** [comment] 2019-12-18 16:34
With the latest version the challenges don't work ..

**Comment by BONNe** [comment] 2019-12-18 17:08
https://github.com/BentoBoxWorld/Challenges/releases/tag/0.8.0

**Comment by BONNe** [comment] 2019-12-27 09:11
I will close this issue. 
I cannot reproduce and no additional information is provided if the updating solved a bug with challenges.

**Closed by BONNe** 2019-12-27 09:11 UTC
Labels: Bug 💥, Cannot replicate 🔂
