### ISSUE TITLE
ArrayIndexOutOfBoundsException: 55 with default challenges

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/Challenges#166] opened 2019-08-14 20:08 UTC
### Description

There is an `ArrayIndexOutOfBoundsException: 55` upon trying to open the player Challenges GUI right after having imported the default challenges. 

#### Steps to reproduce the behavior:

0. Fresh install - no island, nothing
1. Create an island
2. `/bsb challenges` and click on `Import Default Challenges`
3. `/is challenges`

#### Server / BentoBox information:

```
Running SPIGOT 1.13.2.
BentoBox version: 1.6.0
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
BSkyBlock 1.6.0-SNAPSHOT-b436 (ENABLED)
Challenges 0.8.0-SNAPSHOT-#323 (ENABLED)
```

#### Screenshots / Server log

None.

#### Expected behavior / Additional context

Full error printout:
```
[22:02:14 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is challenges' in world.bentobox.bskyblock.commands.IslandCommand(island)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 55
        at java.util.stream.SortedOps$SizedRefSortingSink.accept(Unknown Source) ~[?:1.8.0_191]
        at java.util.TreeMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_191]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_191]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_191]
        at world.bentobox.challenges.ChallengesManager.lambda$getAllChallenges$15(ChallengesManager.java:1405) ~[?:?]
        at java.util.Optional.map(Unknown Source) ~[?:1.8.0_191]
        at world.bentobox.challenges.ChallengesManager.getAllChallenges(ChallengesManager.java:1401) ~[?:?]
        at world.bentobox.challenges.ChallengesManager.getFreeChallenges(ChallengesManager.java:1418) ~[?:?]
        at world.bentobox.challenges.panel.user.ChallengesGUI.addFreeChallenges(ChallengesGUI.java:148) ~[?:?]
        at world.bentobox.challenges.panel.user.ChallengesGUI.build(ChallengesGUI.java:94) ~[?:?]
        at world.bentobox.challenges.commands.ChallengesCommand.execute(ChallengesCommand.java:80) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        ... 14 more
```

**Comment by BONNe** [comment] 2019-08-14 20:57
For me, it looks like an internal java lambda processing issue.
I could not reproduce it.
And as @Poslovitch in discord mentioned, restart fixed it.
I will close it for now.

**Closed by BONNe** 2019-08-14 20:57 UTC
Labels: Bug 💥
