### ISSUE TITLE
Problem with challenges

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/Challenges#44] opened 2018-12-31 12:28 UTC
Why when I try to do / to the challenges I get this error in the console and does not show me the challanges?
I tried both leaving the default file and changing it but the problem is always there. Inside the file there are the challanges but for the plugin it is as if it were empty apparently ..

`[BentoBox] There are no challenges set up!`

**Comment by Poslovitch** [comment] 2018-12-31 12:31
Duplicate of https://github.com/BentoBoxWorld/Challenges/issues/37

**Closed by Poslovitch** 2018-12-31 12:31 UTC
