### ISSUE TITLE
[BentoBox] Could not save object world.bentobox.challenges.database.object.Challenge Incorrect string value: '\xE6\x94\xB6\xE9\x9B\x86...' for column 'uniqueId' at row 1

### ISSUE THREAD

**Issue by hed516** [BentoBoxWorld/Challenges#319] opened 2023-05-06 01:15 UTC
### Expected behavior

[BentoBox] Could not save object world.bentobox.challenges.database.object.Challenge Incorrect string value: '\xE6\x94\xB6\xE9\x9B\x86...' for column 'uniqueId' at row 1

### Observed/Actual behavior

[BentoBox] Could not save object world.bentobox.challenges.database.object.Challenge Incorrect string value: '\xE6\x94\xB6\xE9\x9B\x86...' for column 'uniqueId' at row 1

### Steps/models to reproduce

[BentoBox] Could not save object world.bentobox.challenges.database.object.Challenge Incorrect string value: '\xE6\x94\xB6\xE9\x9B\x86...' for column 'uniqueId' at row 1

### BentoBox version

[BentoBox] Could not save object world.bentobox.challenges.database.object.Challenge Incorrect string value: '\xE6\x94\xB6\xE9\x9B\x86...' for column 'uniqueId' at row 1

**Comment by BONNe** [comment] 2023-05-06 13:06
What name did you write for Challenge?

**Comment by tastybento** [comment] 2023-05-10 23:49
Assume dupe of https://github.com/BentoBoxWorld/Biomes/issues/119

**Closed** 2023-05-13 20:24 UTC
Labels: Status: Duplicate
